### ISSUE TITLE
\n in header column

### ISSUE THREAD

**Issue by jrfoell** [No3x/wp-mail-logging#70] opened 2018-04-03 18:12 UTC
I noticed a '\n' in the header column in wp-admin. I believe it's b/c the string in implode here: https://github.com/No3x/wp-mail-logging/blob/master/WPML_Plugin.php#L198 (and in extractReceiver() above it) are encased in a single-quote string rather than a double-quote string, which should allow the \n character to get rendered as desired.

**Comment by No3x** [comment] 2018-04-04 13:35
Duplicate of #55?

**Comment by jrfoell** [comment] 2018-04-04 13:46
Possibly, so it's done that way on purpose?

**Comment by No3x** [comment] 2018-04-04 13:50
As stated in the other issue:
> Converting \n to line breaks would inflate the row height.
I want to show the raw-header information in this column.

But you can try to convince me with a better solution. So you would like to see each entry row by row?

**Comment by jrfoell** [comment] 2018-04-04 13:58
I think it just caught me off-guard b/c it looked weird. I would suggest if you keep it to put a note in the FAQ about it :)

**Comment by No3x** [comment] 2018-04-04 14:01
Yeah, it looks pretty weird but I don't have a better solution. I could use `,` as delimiter or `<pre>`.

**Closed** 2018-04-12 07:55 UTC
