### ISSUE TITLE
Potential bug? Problem with using redux-framework?

### ISSUE THREAD

**Issue by jonasskafte** [No3x/wp-mail-logging#73] opened 2018-05-31 09:00 UTC
Hi there,

Firstly, many thanks for providing such a great plugin to the WP community!

Yesterday I experienced an odd issue where, for some reason, the WooCommerce order confirmation page failed to generate. I contacted my host and here’s what they said:

—

For some reason, WordPress was timing out while trying to run a database query.
Here is the error we where getting:

`WordPress database error Lock wait timeout exceeded; try restarting transaction for query UPDATEwp_29pvpbg1xo_optionsSEToption_value= ‘1527694195’ WHEREoption_name= ‘_transient_timeout__redux_activation_redirect’`

I manually updated that value in the database and everything seems to be working now.

I believe the plugin wp-mail-logging was the one that was trying to make the query, possibly using wp-cron, as we were also seeing slow errors coming from that plugin at the same time.

–

I am afraid that I don’t really understand the error message they shared with me, but I thought it would be good to share it with you guys and tell you about the problem I had. Hopefully it can be useful in further improving this otherwise great plugin!

Many thanks!

**Comment by No3x** [comment] 2018-06-05 18:43
Hi @jonasskafte,

thanks for your kind words.
I just searched in my logs using the plugin since over 5 years and could not find such an error. I have never seen this before and so it's very hard to reproduce.
Can you tell how your cronjob is executed (or is your WordPress managed by your host)?

**Comment by jonasskafte** [comment] 2018-06-07 19:33
Hi there @No3x,

Apologies for my slow response. Just wanted to ask my host first before I got back to you and they've just confirmed that it's just the standard WP cron.

Since you don't seem to recognise this problem and since I haven't experienced it again since then, perhaps we should just let it be and I can let you know if it happens again – that is unless if you want to dig further and work it out of course 🧐

Many thanks!

**Comment by No3x** [comment] 2018-06-08 08:36
I think that's the best solution. I will close this issue and wait for other users or reoccurrence before reopening it.

**Comment by jonasskafte** [comment] 2018-06-22 13:02
Hi there @No3x,

Hope you are well.

Just wanted to let you know that this problem has just reoccurred for me. I missed out on 3 orders because of it, and so now I don't dare to continue using the plugin until it's been fixed. I'm afraid I cannot give you any more information about why happened, but as soon as I disabled 'WP Mail Logging' the problem then disappeared and everything was fine again... From reading the error message I reckon it might have to do with using redux-framework?

Anyway, I hope to see a fix to this. In the meantime, I'll start looking for other mail logging options, just in case – although I hope I'll be able to continue using your otherwise great plugin!

Many thanks and all the best.

**Comment by No3x** [comment] 2018-06-22 14:32
Hi @jonasskafte,
thanks I'm fine. How are you?

I just want to inform you that I found a plugin that had the same trouble. I have contacted the plugin author and asked how he fixed the issue.

I looked for the cause of this error. To me it seems like you have a site with high traffic and the database is too slow to respond. Other plugins or database operations of WordPress should also yield this error then.
The code that causes this problem is not under my control directly. I use a options framework called redux. I could update this dependency and see if they added some checks to avoid this.

In the meantime please check if `innodb_lock_wait_timeout` in your database config is configured appropriately.

**Comment by No3x** [comment] 2018-06-22 14:41
I did a quick compare of the current version of the library bundled with my plugin and a newer version of the library author. The line that sets the`redux_activation_redirect` was removed in the meantime. I think this should solve the issue.
I will release a new plugin version soon.

**Comment by jonasskafte** [comment] 2018-06-22 14:42
Thanks for the update @No3x – sounds great!

**Closed** 2018-06-22 15:33 UTC

**Comment by No3x** [comment] 2019-04-05 20:24
Updated to redux 3.6.12 and verified the removal of this line.
